"""X14 — observation→action loop closure (acceptance plan §5, case X14).

X14: every fact a probe/lineage report emits must either (a) resolve to a
registered, dispatchable action, or (b) carry a written no-action contract;
every action id sent outward must be in the registry; and no rule may be
unable to fail.

This file grounds the *closure* end to end, complementing (not repeating) the
per-gap tests:

- **probe ids** — enumerated statically from ``commands/probe.py`` AND from
  real ``probe <module> --json`` runs on the e2e fixture vault; each must be
  registered or a declared non-registry (UI-only) action.  The product-side
  table and construction guard are #223 (tests/test_action_registry.py); this
  file proves *source + live* enumeration against it.
- **facet states** — every per-paper facet state the lineage probe reports,
  including ``unknown``, must map to a registered action or an explicit
  no-action contract (``reconcile.FACET_STATES`` / ``FACET_REPAIR_ACTIONS`` /
  ``FACET_NO_ACTION``).
- **unfailable rule** — #220; already covered by
  ``tests/test_architecture_audit_reconcile.py::TestRuleSubjectBinding``
  (``test_unbound_subject_is_not_satisfied`` and
  ``test_unbound_subject_makes_the_audit_ineligible``), so it is referenced,
  never re-implemented here.
- **W2 attempt** — a direct ``paperforge action run`` of an automatic action
  settles the same overwrite-only last-attempt record as the follow-up chain,
  so the reconcile re-emission gate cannot be bypassed by skipping the chain.
"""

from __future__ import annotations

import ast
import importlib.util
import json
import os
import shutil
import subprocess
import sys
from collections.abc import Iterable
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
PROBE_SOURCE = ROOT / "paperforge" / "commands" / "probe.py"
RECONCILE_SOURCE = ROOT / "paperforge" / "reconcile.py"
BUILDER = ROOT / "paperforge" / "plugin" / "test" / "fixtures" / "build_e2e_vault.py"
KEY = "TSTONE001"

PROBE_MODULES = (
    "installation",
    "help",
    "library",
    "ocr",
    "memory",
    "maintenance",
    "lineage",
    "all",
)

#: The module stems whose ``<stem>.probe`` retry id ``probe`` builds dynamically
#: from ``PROBE_ORDER`` (``f"{mod_name}.probe"``).
PROBE_ORDER_STEMS = ("installation", "library", "ocr", "memory", "help")


# ── fixtures ──────────────────────────────────────────────────────────────


def _env(home: Path) -> dict[str, str]:
    env = dict(os.environ)
    env.update(
        HOME=str(home),
        USERPROFILE=str(home),
        PYTHONIOENCODING="utf-8",
        PYTHON_KEYRING_BACKEND="keyring.backends.null.Keyring",
    )
    for name in list(env):
        if name.startswith("PAPERFORGE_CREDENTIAL_"):
            env.pop(name)
    return env


def _pf(vault: Path, home: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, "-m", "paperforge", "--vault", str(vault), *args],
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        env=_env(home),
        timeout=170,
    )


@pytest.fixture(scope="module")
def built_vault(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """The e2e vault, generated by its own builder (real sync) into a tmp dir.

    The plugin's ``test/vaults/e2e`` is untracked build output, so the builder
    is loaded with its target paths redirected instead of reading that copy.
    """
    spec = importlib.util.spec_from_file_location("_x14_build_e2e_vault", BUILDER)
    assert spec and spec.loader
    builder = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(builder)
    root = tmp_path_factory.mktemp("x14-fixture")
    builder.VAULT = root / "e2e"
    builder.EMPTY_VAULT = root / "empty"
    builder.build()
    return builder.VAULT


@pytest.fixture
def synced_copy(tmp_path: Path, built_vault: Path) -> tuple[Path, Path]:
    """A private, synced copy of the fixture vault (tests must not share it)."""
    vault = tmp_path / "vault"
    home = tmp_path / "home"
    home.mkdir()
    shutil.copytree(built_vault, vault)
    result = _pf(vault, home, "sync", "--json")
    assert result.returncode == 0, result.stdout[-2000:] + result.stderr[-2000:]
    return vault, home


# ── (a) probe action ids ──────────────────────────────────────────────────


def _static_probe_action_ids() -> set[str]:
    """Every ``action_id`` the probe can place in an envelope, from source.

    Reads the keyword arguments of the product's own ``build_action_primary``
    calls — no hand-maintained list — and expands the one dynamic id
    (``f"{mod_name}.probe"`` over ``PROBE_ORDER``).
    """
    tree = ast.parse(PROBE_SOURCE.read_text(encoding="utf-8"))
    ids: set[str] = set()
    dynamic: list[str] = []
    for node in ast.walk(tree):
        if not (isinstance(node, ast.keyword) and node.arg == "action_id"):
            continue
        value = node.value
        if isinstance(value, ast.Constant) and isinstance(value.value, str):
            ids.add(value.value)
        elif isinstance(value, ast.IfExp):
            for branch in (value.body, value.orelse):
                assert isinstance(branch, ast.Constant) and isinstance(branch.value, str)
                ids.add(branch.value)
        elif isinstance(value, ast.JoinedStr):
            parts: list[str] = []
            for piece in value.values:
                if isinstance(piece, ast.Constant):
                    parts.append(str(piece.value))
                elif isinstance(piece, ast.FormattedValue) and isinstance(
                    piece.value, ast.Name
                ):
                    parts.append("{" + piece.value.id + "}")
                else:  # pragma: no cover - guards a new dynamic shape
                    raise AssertionError(f"unhandled probe action_id piece: {ast.dump(piece)}")
            dynamic.append("".join(parts))
        else:  # pragma: no cover - guards a new dynamic shape
            raise AssertionError(f"unhandled probe action_id expr: {ast.dump(value)}")
    for expr in dynamic:
        assert expr == "{mod_name}.probe", f"new dynamic probe id: {expr!r}"
        ids |= {f"{stem}.probe" for stem in PROBE_ORDER_STEMS}
    assert ids, "static probe enumeration found no action ids"
    return ids


def _unclassified_action_ids(action_ids: Iterable[str]) -> list[str]:
    """Ids nothing can execute: neither registered nor a declared non-registry
    (UI-only) action.  Non-empty means a dead control reached a user."""
    from paperforge.actions.registry import ACTION_REGISTRY, NON_REGISTRY_ACTIONS

    executable = set(ACTION_REGISTRY) | set(NON_REGISTRY_ACTIONS)
    return sorted(set(action_ids) - executable)


def _live_probe_action_ids(vault: Path, home: Path) -> set[str]:
    """Every ``action_id`` a real ``probe <module> --json`` envelope emits."""
    found: set[str] = set()
    for module in PROBE_MODULES:
        result = _pf(vault, home, "probe", module, "--json")
        assert result.returncode == 0, (module, result.stderr[-1500:])
        envelope = json.loads(result.stdout)

        def walk(obj: object) -> None:
            if isinstance(obj, dict):
                if isinstance(obj.get("action_id"), str):
                    found.add(obj["action_id"])
                for value in obj.values():
                    walk(value)
            elif isinstance(obj, list):
                for value in obj:
                    walk(value)

        walk(envelope)
    return found


def test_every_static_probe_action_id_is_executable() -> None:
    static = _static_probe_action_ids()
    assert _unclassified_action_ids(static) == []


def test_every_live_probe_action_id_is_executable(built_vault: Path, tmp_path: Path) -> None:
    home = tmp_path / "home"
    home.mkdir()
    live = _live_probe_action_ids(built_vault, home)
    assert live, "no probe module advertised an action id"
    assert _unclassified_action_ids(live) == []
    # The live ids are a subset of the static enumeration — the static gate
    # above therefore covers whatever a real run can emit.
    assert live <= _static_probe_action_ids(), live - _static_probe_action_ids()


def test_unregistered_action_id_is_refused() -> None:
    """Negative control: the checker fails on an id nothing can dispatch."""
    from paperforge.actions.registry import UnknownActionId, classify_action_id

    bogus = "not.a.real.probe.action"
    assert _unclassified_action_ids([bogus]) == [bogus]
    with pytest.raises(UnknownActionId):
        classify_action_id(bogus)


# ── (a′) reconcile's own outward action ids ───────────────────────────────


def _static_reconcile_action_ids() -> set[str]:
    """Every ``ActionIntent(action_id=...)`` literal reconcile can emit."""
    tree = ast.parse(RECONCILE_SOURCE.read_text(encoding="utf-8"))
    ids: set[str] = set()
    for node in ast.walk(tree):
        if not (isinstance(node, ast.keyword) and node.arg == "action_id"):
            continue
        value = node.value
        if isinstance(value, ast.Constant) and isinstance(value.value, str):
            ids.add(value.value)
        else:
            # The only non-literal is the digest helper re-wrapping its own
            # ``action_id`` parameter — never an emitted id.
            assert isinstance(value, ast.Name) and value.id == "action_id", ast.dump(value)
    assert ids
    return ids


def test_reconcile_emits_only_the_declared_actions() -> None:
    """The W2 direct-run gate keys off RECONCILE_ACTIONS — it must equal the
    ids reconcile actually emits, and every one must be registered."""
    from paperforge.actions.registry import ACTION_REGISTRY
    from paperforge.reconcile import RECONCILE_ACTIONS

    emitted = _static_reconcile_action_ids()
    assert emitted == set(RECONCILE_ACTIONS), (emitted, set(RECONCILE_ACTIONS))
    assert _unclassified_action_ids(emitted) == []
    assert emitted <= set(ACTION_REGISTRY)


# ── (b) facet-state closure ───────────────────────────────────────────────


def _probe_function_return_literals(module: Path, names: set[str]) -> set[str]:
    """String literals returned by the named functions (lineage state probes).

    A partial static grounding only: the ocr values assembled from
    ``top_state``/``identity_state`` variables are covered by FACET_STATES.
    """
    tree = ast.parse(module.read_text(encoding="utf-8"))
    found: set[str] = set()
    for fn in ast.walk(tree):
        if not (isinstance(fn, ast.FunctionDef) and fn.name in names):
            continue
        for node in ast.walk(fn):
            if (
                isinstance(node, ast.Return)
                and isinstance(node.value, ast.Constant)
                and isinstance(node.value.value, str)
            ):
                found.add(node.value.value)
    return found


def test_facet_contract_is_well_formed() -> None:
    from paperforge.reconcile import validate_facet_contract

    assert validate_facet_contract() == []


def test_facet_vocabulary_covers_the_probe_source() -> None:
    """A new literal state in a lineage probe must force a contract update."""
    from paperforge.reconcile import FACET_STATES

    probe_literals = _probe_function_return_literals(
        ROOT / "paperforge" / "lineage.py",
        {"_probe_ocr_state", "_probe_retrieval_state", "_probe_vector_state"},
    )
    assert {"current", "stale", "missing", "unknown"} <= probe_literals
    # Every literal is a real facet state for at least one layer.
    known = {state for states in FACET_STATES.values() for state in states}
    assert probe_literals <= known, probe_literals - known


def _facet_observation(layer: str, state: str):
    """A PaperObservation isolating one layer's state; other layers current."""
    from paperforge.reconcile import PaperObservation

    base = {"ocr": "current", "retrieval": "current", "vector": "current"}
    base[layer] = state
    return PaperObservation(
        key="KEY1",
        ocr=base["ocr"],
        retrieval=base["retrieval"],
        vector=base["vector"],
        identities={},
        details=None,
    )


def test_every_facet_state_closes_to_action_or_no_action() -> None:
    """Each declared state maps ONLY to its declared actions (or none) — the
    X14 closure property.  A state that quietly emitted an undeclared action
    (or a repairable state that emitted nothing) fails here."""
    from paperforge.reconcile import (
        FACET_REPAIR_ACTIONS,
        FACET_STATES,
        _per_paper_intents,
    )

    for layer, states in FACET_STATES.items():
        for state in states:
            declared = set(FACET_REPAIR_ACTIONS.get((layer, state), ()))
            emitted = {
                intent.action_id for intent in _per_paper_intents(_facet_observation(layer, state))
            }
            assert emitted <= declared, (layer, state, emitted, declared)
            if declared:
                # A repairable state must actually repair — no dead mapping.
                assert emitted, (layer, state, "declared repair never emitted")


def test_unknown_facet_states_emit_no_intent() -> None:
    """``unknown`` is a first-class fail-closed state: no intent, never
    interpreted as stale (design §2.3).  The reconcile-level reason string is
    asserted in tests/test_reconcile.py::TestMinimalFrontier."""
    from paperforge.reconcile import FACET_NO_ACTION, _per_paper_intents

    for layer in ("ocr", "retrieval", "vector"):
        assert (layer, "unknown") in FACET_NO_ACTION
        assert _per_paper_intents(_facet_observation(layer, "unknown")) == []


def test_uncontracted_facet_state_is_surfaced(monkeypatch, tmp_path: Path) -> None:
    """Fail closed: a facet state outside the contract is reported, not
    dropped — otherwise a new probe state would pass in silence."""
    import paperforge.reconcile as reconcile_module
    from paperforge.reconcile import PaperObservation, reconcile

    bogus = PaperObservation(
        key="KEY1", ocr="bogus_state", retrieval="current", vector="current",
        identities={}, details=None,
    )
    monkeypatch.setattr(
        reconcile_module,
        "observe",
        lambda vault, keys=None: reconcile_module.ReconcileObservation(
            global_state=reconcile_module.GlobalObservation(
                memory_substrate_ok=True, vector_substrate_ok=True
            ),
            papers=(bogus,),
            vault=vault,
        ),
    )
    # No intents are emitted (no contract key), so the gateway only needs the
    # (empty) last-attempt read; the vault itself is never touched.
    monkeypatch.setattr(reconcile_module, "read_last_attempts", lambda vault: {})
    result = reconcile(tmp_path)
    assert "reconcile.facet_uncontracted:KEY1:ocr:bogus_state" in result.data["diagnostics"]


# ── (d) direct `action run` settles the same W2 attempt ───────────────────


def test_direct_action_run_settles_the_chain_w2_record(synced_copy) -> None:
    """Gap: the W2 attempt was written only by the chain; a direct
    ``action run`` bypassed it.  Now it settles the same record the chain
    computes (`semantic_attempt_digest`), so the reconcile gate consumes it."""
    vault, home = synced_copy
    result = _pf(
        vault, home,
        "action", "run", "ocr.rebuild_derived",
        "--scope", "papers", "--key", KEY, "--json",
    )
    assert result.returncode == 0, result.stdout[-2000:] + result.stderr[-2000:]

    from paperforge.reconcile import read_last_attempts, semantic_attempt_digest

    attempts = read_last_attempts(vault)
    record = attempts.get(f"ocr.rebuild_derived:papers:{KEY}")
    assert record is not None, attempts
    assert record["outcome"] == "succeeded"
    # Same digest the chain path records for this very intent.
    chain_digest = semantic_attempt_digest(
        vault,
        {"action_id": "ocr.rebuild_derived", "scope": {"kind": "papers", "keys": [KEY]}},
    )
    assert record["input_digest"] == chain_digest


def test_predispatch_failure_settles_nothing(synced_copy) -> None:
    """Only a DISPATCHED attempt settles: rc3 (confirmation required) is not a
    failed attempt and must not create a record."""
    vault, home = synced_copy
    result = _pf(vault, home, "action", "run", "memory.build", "--json")
    assert result.returncode == 3, result.stdout[-1500:] + result.stderr[-1500:]

    from paperforge.reconcile import read_last_attempts

    assert read_last_attempts(vault) == {}
