"""X13 — queries are read-only (acceptance plan §5, issue #265; #221/#226/#228).

Every entry declared as a read/report runs as a REAL ``python -m paperforge``
subprocess against a synced copy of the e2e fixture vault, and the vault must
be byte-identical afterwards: no file created, deleted or changed.

The only tolerated churn is mtime-only touches of SQLite's shared-memory /
WAL files and the read-lock file that a reader takes; their *content* may not
change and they may not be created by a read.

Edge states are covered too (a user-edited Base view, a missing logs dir, a
missing memory DB, no Bases dir), because the historical writes (#221: status
rewrote ``.base``; dashboard/runtime-health created probe dirs) only fired
when the vault was not in its steady state.

``render audit`` is declared as a writer of its own report (``cli.py`` help,
``docs/COMMANDS.md``) and is asserted to write exactly that file and nothing
else. A mutating control (``base-refresh`` on an edited Base) proves the
detector can fail — X13 requires the gate to be triggerable.
"""

from __future__ import annotations

import hashlib
import os
import shutil
import subprocess
import sys
from pathlib import Path

import importlib.util

import pytest

ROOT = Path(__file__).resolve().parents[1]
BUILDER = ROOT / "paperforge" / "plugin" / "test" / "fixtures" / "build_e2e_vault.py"
KEY = "TSTONE001"

# Tool-owned files a reader may touch (mtime) but never create or change.
TOUCH_ONLY_SUFFIXES = ("-shm", "-wal", ".read.lock")

READ_COMMANDS: list[list[str]] = [
    ["status", "--json"],
    ["dashboard", "--json"],
    ["runtime-health", "--json"],
    ["probe", "all", "--json"],
    ["probe", "lineage", "--json"],
    ["reconcile", "--json"],
    ["doctor", "--json"],
    ["paths", "--json"],
    ["deep-reading", "--json"],
    ["ocr", "list", "--json"],
    ["ocr", "status", "--json"],
    ["ocr", "pipeline-versions", "--json"],
    ["embed", "status", "--json"],
    ["memory", "status", "--json"],
    ["config", "list", "--json"],
    ["config", "validate", "--json"],
    ["config", "paths", "--json"],
    ["auth", "status", "--json"],
    ["action", "list", "--json"],
    ["paper-status", KEY, "--json"],
    ["search", "tendon", "--json"],
    ["agent-context", "--json"],
    ["prune", "--json"],  # dry-run by default
]

# The surfaces whose historical writes were state-dependent.
EDGE_COMMANDS: list[list[str]] = [
    ["status", "--json"],
    ["dashboard", "--json"],
    ["runtime-health", "--json"],
    ["probe", "all", "--json"],
    ["reconcile", "--json"],
    ["doctor", "--json"],
    ["deep-reading", "--json"],
    ["ocr", "list", "--json"],
    ["memory", "status", "--json"],
    ["embed", "status", "--json"],
]


def _env(home: Path) -> dict[str, str]:
    env = dict(os.environ)
    env.update(
        HOME=str(home),
        USERPROFILE=str(home),
        APPDATA=str(home / "AppData" / "Roaming"),
        LOCALAPPDATA=str(home / "AppData" / "Local"),
        PYTHONIOENCODING="utf-8",
        PYTHON_KEYRING_BACKEND="keyring.backends.null.Keyring",
    )
    for name in list(env):
        if name.startswith("PAPERFORGE_CREDENTIAL_"):
            env.pop(name)
    return env


def _pf(vault: Path, home: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, "-m", "paperforge", "--vault", str(vault), *args],
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        env=_env(home),
        timeout=170,
    )


def _snapshot(root: Path) -> dict[str, tuple[str, int]]:
    out: dict[str, tuple[str, int]] = {}
    for path in root.rglob("*"):
        if path.is_file():
            rel = path.relative_to(root).as_posix()
            out[rel] = (hashlib.sha256(path.read_bytes()).hexdigest(), path.stat().st_mtime_ns)
    return out


def _durable_writes(before: dict, after: dict) -> list[str]:
    changes: list[str] = []
    for rel in sorted(after.keys() - before.keys()):
        changes.append(f"created {rel}")
    for rel in sorted(before.keys() - after.keys()):
        changes.append(f"deleted {rel}")
    for rel in sorted(before.keys() & after.keys()):
        if before[rel][0] != after[rel][0]:
            changes.append(f"changed {rel}")
        elif before[rel][1] != after[rel][1] and not rel.endswith(TOUCH_ONLY_SUFFIXES):
            changes.append(f"rewrote {rel} (same bytes)")
    return changes


@pytest.fixture(scope="module")
def built_vault(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """The e2e vault, generated by its own builder (real sync) into a tmp dir.

    The plugin's ``test/vaults/e2e`` is untracked build output, so the builder
    is loaded with its target paths redirected instead of reading that copy.
    """
    spec = importlib.util.spec_from_file_location("_x13_build_e2e_vault", BUILDER)
    assert spec and spec.loader
    builder = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(builder)
    root = tmp_path_factory.mktemp("x13-fixture")
    builder.VAULT = root / "e2e"
    builder.EMPTY_VAULT = root / "empty"
    builder.build()
    return builder.VAULT


@pytest.fixture
def prepare(tmp_path: Path, built_vault: Path):
    def _do(state: str) -> tuple[Path, Path]:
        return _prepare(tmp_path, built_vault, state)

    return _do


def _prepare(tmp_path: Path, source: Path, state: str) -> tuple[Path, Path]:
    vault = tmp_path / "vault"
    home = tmp_path / "home"
    home.mkdir()
    shutil.copytree(source, vault)
    synced = _pf(vault, home, "sync", "--json")
    assert synced.returncode == 0, synced.stdout[-2000:] + synced.stderr[-2000:]
    if state == "edited_base":
        bases = sorted((vault / "Bases").glob("*.base"))
        assert bases, "fixture guard: the e2e vault must ship Base views"
        for base in bases:
            base.write_text(
                base.read_text(encoding="utf-8") + "\n# user edit (X13)\n", encoding="utf-8"
            )
    elif state == "no_logs":
        shutil.rmtree(vault / "System" / "PaperForge" / "logs", ignore_errors=True)
    elif state == "no_memory_db":
        dbs = list((vault / "System" / "PaperForge" / "indexes").glob("paperforge.db*"))
        assert dbs, "fixture guard: sync must have built the memory DB"
        for db in dbs:
            db.unlink()
    elif state == "no_bases":
        shutil.rmtree(vault / "Bases")
    else:
        assert state == "steady", state
    return vault, home


def _assert_reads_do_not_write(vault: Path, home: Path, commands: list[list[str]]) -> None:
    offenders: list[str] = []
    for args in commands:
        before = _snapshot(vault)
        result = _pf(vault, home, *args)
        after = _snapshot(vault)
        # Exit 0/1 are reports (doctor fails checks with 1); 2 is a usage error,
        # which would make this case vacuous.
        assert result.returncode in (0, 1), (args, result.returncode, result.stderr[-1500:])
        writes = _durable_writes(before, after)
        if writes:
            offenders.append(f"paperforge {' '.join(args)}: {writes[:8]}")
    assert not offenders, "read/report entries wrote to the vault:\n" + "\n".join(offenders)


@pytest.mark.timeout(900)
def test_read_entries_leave_a_steady_vault_byte_identical(prepare) -> None:
    vault, home = prepare("steady")
    _assert_reads_do_not_write(vault, home, READ_COMMANDS)


@pytest.mark.timeout(600)
@pytest.mark.parametrize("state", ["edited_base", "no_logs", "no_memory_db", "no_bases"])
def test_read_entries_do_not_repair_edge_states(prepare, state: str) -> None:
    vault, home = prepare(state)
    _assert_reads_do_not_write(vault, home, EDGE_COMMANDS)


@pytest.mark.timeout(300)
def test_render_audit_writes_only_its_declared_report(prepare) -> None:
    vault, home = prepare("steady")
    report = f"System/PaperForge/ocr/{KEY}/render/render.consistency.json"
    (vault / report).unlink(missing_ok=True)
    before = _snapshot(vault)
    result = _pf(vault, home, "render", "audit", KEY, "--json")
    assert result.returncode in (0, 1), result.stderr[-1500:]
    writes = _durable_writes(before, _snapshot(vault))
    assert writes == [f"created {report}"], writes


@pytest.mark.timeout(300)
def test_detector_fails_on_a_real_write(prepare) -> None:
    # Negative control: a mutating verb on an edited Base view MUST be caught,
    # otherwise the read-only assertions above could pass vacuously.
    vault, home = prepare("edited_base")
    before = _snapshot(vault)
    result = _pf(vault, home, "base-refresh", "--force")
    assert result.returncode == 0, result.stderr[-1500:]
    writes = _durable_writes(before, _snapshot(vault))
    assert any(w.startswith("changed Bases/") for w in writes), writes
