"""PaperForge Architecture Audit — Slice A (#131).

Five immutable layers: Contract, Survey, DeterministicAudit, Review, View.
See layers.py for the model, canonical.py for digests, reconcile.py for the
pure reconciliation engine and compose projection.
"""
from __future__ import annotations

from paperforge.architecture_audit.canonical import (
    canonical_json,
    finding_id,
    semantic_digest,
    sha256_digest,
    stable_id,
)
from paperforge.architecture_audit.layers import (
    SCHEMA_VERSION,
    Adjudication,
    AdjudicationKind,
    ArchitectureContract,
    ArchitectureError,
    ArchitectureReportView,
    ArchitectureReview,
    ArchitectureSurvey,
    Assessment,
    AssessmentStatus,
    AuditContent,
    CanonicalWriteFact,
    Confidence,
    CoverageEntry,
    CoverageStatus,
    DeterministicAudit,
    EffectFact,
    EffectiveAfter,
    EffectKind,
    EnforcementMode,
    EpistemicStatus,
    Evidence,
    EvidenceRequest,
    ExceptionDecl,
    Finding,
    IntentMode,
    KnownGap,
    LifecycleStatus,
    PublicationUnitDecl,
    RoleAuthorityFact,
    Rule,
    RuleCoverage,
    RuleKind,
    RuleStatus,
    SemanticFinding,
    SignalConsumerKind,
    SignalFact,
    UnitAuthorityFact,
    validate_contract,
    validate_review,
    validate_survey,
)
from paperforge.architecture_audit.reconcile import (
    RECONCILER_VERSION,
    DigestMismatch,
    compose,
    reconcile,
)

__all__ = [
    "SCHEMA_VERSION",
    "RECONCILER_VERSION",
    "Adjudication",
    "AdjudicationKind",
    "ArchitectureContract",
    "ArchitectureError",
    "ArchitectureReportView",
    "ArchitectureReview",
    "ArchitectureSurvey",
    "Assessment",
    "AssessmentStatus",
    "AuditContent",
    "CanonicalWriteFact",
    "Confidence",
    "CoverageEntry",
    "CoverageStatus",
    "DeterministicAudit",
    "DigestMismatch",
    "EffectFact",
    "EffectKind",
    "EffectiveAfter",
    "EnforcementMode",
    "EpistemicStatus",
    "Evidence",
    "EvidenceRequest",
    "ExceptionDecl",
    "Finding",
    "IntentMode",
    "KnownGap",
    "LifecycleStatus",
    "PublicationUnitDecl",
    "RoleAuthorityFact",
    "Rule",
    "RuleCoverage",
    "RuleKind",
    "RuleStatus",
    "SemanticFinding",
    "SignalConsumerKind",
    "SignalFact",
    "UnitAuthorityFact",
    "canonical_json",
    "compose",
    "finding_id",
    "reconcile",
    "semantic_digest",
    "sha256_digest",
    "stable_id",
    "validate_contract",
    "validate_review",
    "validate_survey",
]
