"""Integration test: fixture-driven Zotero annotation import workflow.

Requires the fixture at fixtures/zotero/test_annotations.sqlite, which can
be generated by running:
  python fixtures/zotero/build_test_db.py
"""

from __future__ import annotations

import shutil
import sqlite3
import tempfile
from pathlib import Path

import pytest

FIXTURE_DIR = Path(__file__).resolve().parent.parent.parent / "fixtures" / "zotero"
FIXTURE_PATH = FIXTURE_DIR / "test_annotations.sqlite"


@pytest.fixture(scope="session")
def zotero_fixture() -> Path:
    """Ensure the fixture exists (generate if needed)."""
    if not FIXTURE_PATH.exists():
        from fixtures.zotero.build_test_db import build_test_db

        FIXTURE_DIR.mkdir(parents=True, exist_ok=True)
        build_test_db(FIXTURE_PATH)
    return FIXTURE_PATH


@pytest.fixture
def zotero_copy(zotero_fixture: Path) -> Path:
    """Copy the fixture to a temp location for each test."""
    tmp = Path(tempfile.mkdtemp()) / "zotero_copy.sqlite"
    shutil.copy2(str(zotero_fixture), str(tmp))
    yield tmp
    shutil.rmtree(tmp.parent, ignore_errors=True)


@pytest.fixture
def ann_db(tmp_path: Path):
    """Provide a fresh annotation database with schema applied."""
    from paperforge.annotation.db import get_annotations_db_path, get_annotations_connection
    from paperforge.annotation.schema import ensure_schema

    db_path = get_annotations_db_path(tmp_path)
    conn = get_annotations_connection(db_path, read_only=False)
    ensure_schema(conn)
    yield conn
    conn.close()


class TestZoteroImportWorkflow:
    """End-to-end import from a real Zotero-style SQLite fixture."""

    def test_probe_reads_all_annotation_types(self, zotero_copy):
        """Verify probe can read highlight, underline, and note from fixture."""
        from paperforge.annotation.probe import open_readonly, fetch_annotations

        conn = open_readonly(zotero_copy)
        try:
            anns = fetch_annotations(conn, limit=10)
        finally:
            conn.close()

        assert len(anns) == 3
        types = {a["annotationType"] for a in anns}
        assert types == {"highlight", "underline", "note"}

    def test_full_import_pipeline(self, zotero_copy, ann_db):
        """Probe → import → verify."""
        from paperforge.annotation.probe import open_readonly, fetch_annotations
        from paperforge.annotation.importer import run_import
        from paperforge.annotation.service import list_annotations

        # Phase 1: probe
        probe_conn = open_readonly(zotero_copy)
        try:
            anns = fetch_annotations(probe_conn, limit=10)
        finally:
            probe_conn.close()

        assert len(anns) == 3

        # Phase 2: import
        result = run_import(ann_db, anns, source="zotero_db")
        assert result["imported"] == 3
        assert result["updated"] == 0
        assert result["deleted"] == 0

        # Phase 3: verify
        stored = list_annotations(ann_db, paper_id="PAPER001")
        assert len(stored) == 3

        highlight = next(a for a in stored if a["type"] == "highlight")
        assert highlight["selected_text"].startswith("Deep learning")
        assert highlight["color"] == "#ffd400"
        assert highlight["source"] == "zotero_db"
        assert highlight["sync_state"] == "zotero_synced"
        assert highlight["is_readonly"] == 1

        underline = next(a for a in stored if a["type"] == "underline")
        assert underline["selected_text"].startswith("The primary limitation")
        assert underline["color"] == "#ff6666"

        note = next(a for a in stored if a["type"] == "note")
        assert "U-Net" in note["comment"]

    def test_import_is_idempotent(self, zotero_copy, ann_db):
        """Re-importing same data should not create duplicates."""
        from paperforge.annotation.probe import open_readonly, fetch_annotations
        from paperforge.annotation.importer import run_import

        probe_conn = open_readonly(zotero_copy)
        try:
            anns = fetch_annotations(probe_conn, limit=10)
        finally:
            probe_conn.close()

        r1 = run_import(ann_db, anns, source="zotero_db")
        r2 = run_import(ann_db, anns, source="zotero_db")

        assert r1["imported"] == 3
        assert r2["imported"] == 0
        assert r2["updated"] == 0

        count = ann_db.execute(
            "SELECT COUNT(*) as cnt FROM annotations WHERE deleted_at IS NULL"
        ).fetchone()["cnt"]
        assert count == 3

    def test_reimport_updated_annotation(self, zotero_copy, ann_db):
        """Import, modify fixture version, reimport — verify update."""
        from paperforge.annotation.probe import open_readonly, fetch_annotations
        from paperforge.annotation.importer import run_import

        probe_conn = open_readonly(zotero_copy)
        try:
            anns = fetch_annotations(probe_conn, limit=10)
        finally:
            probe_conn.close()

        run_import(ann_db, anns, source="zotero_db")

        # Simulate updated annotation by changing the fixture
        zotero_copy2 = zotero_copy  # not modifying, just changing the dict
        anns[0]["comment"] = "Updated comment"
        anns[0]["version"] = 4

        result = run_import(ann_db, anns, source="zotero_db")
        assert result["updated"] >= 1

        stored = ann_db.execute(
            "SELECT comment, source_version FROM annotations WHERE zotero_key = ?",
            (anns[0]["annotationKey"],),
        ).fetchone()
        assert stored["comment"] == "Updated comment"
        assert stored["source_version"] == 4


class TestMemoryRebuildSurvival:
    """Annotations must survive memory layer rebuilds."""

    def test_annotations_survive_memory_build(self, zotero_copy, tmp_path):
        """Import annotations → run memory build → verify annotations still exist."""
        from paperforge.annotation.probe import open_readonly, fetch_annotations
        from paperforge.annotation.importer import run_import
        from paperforge.annotation.db import get_annotations_db_path, get_annotations_connection
        from paperforge.annotation.schema import ensure_schema

        # Setup: import annotations
        ann_db_path = get_annotations_db_path(tmp_path)
        ann_conn = get_annotations_connection(ann_db_path, read_only=False)
        ensure_schema(ann_conn)

        probe_conn = open_readonly(zotero_copy)
        try:
            anns = fetch_annotations(probe_conn, limit=10)
        finally:
            probe_conn.close()

        import_result = run_import(ann_conn, anns, source="zotero_db")
        assert import_result["imported"] == 3
        ann_conn.close()

        # Simulate memory build by touching paperforge.db (which shouldn't
        # affect annotations.db since they are separate databases)
        from paperforge.memory.db import get_memory_db_path, get_connection
        from paperforge.memory.schema import ensure_schema as ensure_memory_schema

        mem_db_path = get_memory_db_path(tmp_path)
        mem_conn = get_connection(mem_db_path, read_only=False)
        # This is what memory build does — drop and recreate the memory schema
        from paperforge.memory.schema import drop_all_tables
        drop_all_tables(mem_conn)
        ensure_memory_schema(mem_conn)
        mem_conn.close()

        # Verify: annotations should still be in annotations.db
        ann_conn2 = get_annotations_connection(ann_db_path, read_only=True)
        try:
            count = ann_conn2.execute(
                "SELECT COUNT(*) as cnt FROM annotations WHERE deleted_at IS NULL"
            ).fetchone()["cnt"]
            assert count == 3, f"Expected 3 annotations after memory rebuild, got {count}"
        finally:
            ann_conn2.close()
